# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "push"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    # Clone the master branch. Or, use ${{CF_BRANCH}} to get branch name from trigger
    # Learn more at https://codefresh.io/docs/docs/codefresh-yaml/variables/
    # revision: "master"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "vasilscf/vasil-alpine-prod-vasil-acc"
    working_directory: "${{clone}}"
    # Set 'latest' tag on the image. Or, use built-in variables
    # like ${{CF_BRANCH_TAG_NORMALIZED}} to use the current branch name/tag.
    tag: ${{CF_SHORT_REVISION}}
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: false
    # registry: dockerhub-registry

  push:
    stage: 'push'
    type: push
    title: Pushing to a registry
    candidate: ${{build}}
    tag: ${{CF_SHORT_REVISION}}-push
    # registry: dockerhub-registry

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls -l"
    stage: "test"
